### ISSUE TITLE
Missing Elements In Lobe Interface

### ISSUE THREAD

**Issue by Talk2Giuseppe** [SenshiSentou/sd-webui-tinycards#2]
I understand in advance that the issue may be ignored as it may apply to A1111 indirectly.

The slider is missing when used with the Lobe Theme / Interface, (https://github.com/lobehub/sd-webui-lobe-theme).  But only when the right panel is turned off.  The slider is available when the right panel is enabled.  The issue with Tiny Card when in the panel is that you can't access the card details.  Click on the wrench simply closes the card.  There are other UI issues too where when the card expands, the wrench goes off screen.  The only other way to access the details of the checkpoint and lora cards is to disable the right panel within Lobe.

Also, while on the subject, the ability to control the point size on the cards would be a warm welcome.  Right now, each line of the text is on top of each other making it difficult to read when the cards are in a tiny state.

I do hope the issue can be easily fixed, as these two extension making A1111 so much more pleasurable to work with.

![image](https://github.com/SenshiSentou/sd-webui-tinycards/assets/66699538/930042c0-b75b-41d2-9350-19c24369a37b)

![image](https://github.com/SenshiSentou/sd-webui-tinycards/assets/66699538/8f2d76d1-58b0-4476-85ab-f7ae5398850a)

**Comment by SenshiSentou** [comment]
Hiya,

I've never looked at Lobe before, but I fear this will likely just be a case of two addons conflicting. All TC really adds is some very minimal CSS to introduce the scale factor, set its display, and z-index when hovered over. My guess is Lobe is adding a lot of CSS themselves that doesn't play nice with this, which would explain the text not scaling nicely and the card getting cut off.

I might take a look and see if I can make it compatible, but no promises on if and when. Lobe seems pretty focused on UX and productivity boosters though; perhaps you could poke them and ask them to implement this feature themselves? (They'd be more than welcome to yoink from this repo, but they'd probably wanna do their own thing)
